server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    # This IS the registry, so it doesn't need to register with itself or fetch a registry
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
